name: Continous Builds

on:
  push:
    branches: [ master ]

jobs:

  job_1:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v2
        - name: install qt5
          run: |
             sudo add-apt-repository ppa:beineri/opt-qt-5.15.2-bionic
             sudo apt-get update
             sudo apt-get install libgl1-mesa-dev qt515base qt515webengine qt515webchannel qt515multimedia qt515svg 
        - name: build
          run: |
              export QTDIR=/opt/qt515
              export PATH=/opt/qt515/bin:$PATH
              qmake src/OpenJournal.pro CONFIG+=released
              make
              make clean
        - name: appimage
          run: |
              cd build
              export QTDIR=/opt/qt515
              export PATH=/opt/qt515/bin:$PATH
              wget -O deploy.AppImage https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
              chmod +x deploy.AppImage
              cp ../io.github.bgallois.openjournal.desktop .
              cp ../resources/openjournal.png .
              ./deploy.AppImage io.github.bgallois.openjournal.desktop -no-translations -bundle-non-qt-libs -appimage
              mv OpenJournal*.AppImage OpenJournal-x86_64.AppImage
        - name: Linux artefact
          uses: actions/upload-artifact@v1
          with:
            name: OpenJournalLinux
            path: ./build/OpenJournal-x86_64.AppImage
  job_2:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        - uses: ilammy/msvc-dev-cmd@v1
        - uses: jurplel/install-qt-action@v2
          with:
            host: 'windows'
            target: 'desktop'
            arch: 'win64_msvc2019_64'
            dir: '${{ github.workspace }}/Qt/'
            install-deps: 'true'
            modules: 'qtwebengine qtmultimedia'
            cached: 'false'
        - name: build
          shell: cmd
          run : |
               choco install nsis
               cd src/
               qmake OpenJournal.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
               nmake release
               mkdir OpenJournal
               cp build/OpenJournal.exe OpenJournal/OpenJournal.exe
               windeployqt OpenJournal/OpenJournal.exe
               7z a C:\OpenJournal.zip OpenJournal/
               cd ..
               makensis.exe /V3 resources/installer.nsi
        - name: Windows artefact
          uses: actions/upload-artifact@v1
          with:
            name: OpenJournalWindows
            path: C:/OpenJournal.zip
        - name: Windows artefact installer
          uses: actions/upload-artifact@v1
          with:
            name: OpenJournalWindowsInstaller
            path: C:/OpenJournalInstaller.exe

  job_3:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
        - uses: jurplel/install-qt-action@v2
          with:
            host: 'mac'
            target: 'desktop'
            dir: '${{ github.workspace }}/Qt/'
            install-deps: 'true'
            modules: 'qtwebengine'
            cached: 'false'
            extra: '--external 7z'
        - name: install
          run: |
              brew install sqlite
        - name: build
          run: |
              qmake src/OpenJournal.pro
              make
              cd build/
              macdeployqt OpenJournal.app -always-overwrite -verbose=0
              wget https://raw.githubusercontent.com/arl/macdeployqtfix/master/macdeployqtfix.py
              #python2.7 macdeployqtfix.py OpenJournal.app/Contents/MacOS/OpenJournal ../../Qt/5.15.0/
              hdiutil create -volname OpenJournal -srcfolder OpenJournal.app -ov -format UDZO OpenJournal.dmg


        - name: Mac artefact
          uses: actions/upload-artifact@v1
          with:
            name: OpenJournalMac
            path: ./build/OpenJournal.dmg

