name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: install qt5
      run: |
        sudo apt-get update
        sudo apt-get install build-essential cmake libgl1-mesa-dev
        sudo apt-get install libgtest-dev
        pip install aqtinstall
        python3 -m aqt install-qt -m qtwebengine -O ${{ github.workspace }}/Qt/ linux desktop 5.15.2
        echo ${{ github.workspace }}/Qt/5.15.2/gcc_64/bin/ >> $GITHUB_PATH
    - name: test
      run: |
        export QT_QPA_PLATFORM=offscreen
        qmake test/Test.pro
        make check
